version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: estacio
      POSTGRES_PASSWORD: est4cio@
      POSTGRES_DB: estacio
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  
      - ./database/migrations:/docker-entrypoint-initdb.d 

  backend-api:
    build: ./backend-api
    container_name: backend-api
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    volumes:
      - ./backend-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network

  backend-authentication:
    build: ./backend-authentication
    container_name: backend-authentication
    depends_on:
      - postgres
    ports:
      - "3002:3000"
    volumes:
      - ./backend-authentication:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend-api
      - backend-authentication
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network
  
networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:

#   shared-volume:
#     driver: local
#     driver_opts:
#       type: none
#       device: in  
#       o: bind
