import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import * as ReactQuery from "@/lib/config/react-query";

const inter = Inter({
  variable: "--font-inter",
  preload: true,
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <ReactQuery.Provider>
          {children}
        </ReactQuery.Provider>
      </body>
    </html>
  );
}
